# Studio Visual QA Rule
# 스튜디오 시각화 검증 루틴

id: studio-visual-qa-001
name: 스튜디오 시각화 검증
description: |
  프로젝트 추가 또는 기능 변경 시, 스튜디오 대시보드의 시각화 상태를
  자동으로 검증하고 보완하는 루틴.
  접근성(중학생/비개발자 타겟)을 항상 유지한다.

category: workflow/studio-qa
tags:
  - studio
  - visualization
  - accessibility
  - qa
  - dashboard

severity: warning

trigger:
  when:
    - "projects/ 디렉토리에 새 프로젝트 추가"
    - "studio/data/projects.js 데이터 변경"
    - "studio/js/app.js 렌더링 로직 변경"
    - "studio/css/style.css 스타일 변경"
    - "studio/index.html 구조 변경"
  keywords:
    - 프로젝트 추가
    - 스튜디오
    - 대시보드
    - 시각화
    - 카드
    - 타임라인

claude_summary:
  - "**트리거**: projects/ 추가, studio/ 파일 변경 시 자동 실행"
  - "**데이터 동기화**: projects.js에 신규 항목이 누락 없는지 확인"
  - "**렌더링 검증**: 카드 부제목, 링크 텍스트, 개념 태그 표시 확인"
  - "**접근성 검증**: 터치 타겟, 폰트 크기, 스킵 링크, 키보드 네비게이션"
  - "**모바일 검증**: 타임라인 스크롤 힌트, 필터 레이아웃, 반응형"

rules:
  data-sync:
    description: "데이터 동기화 검증"
    items:
      - "studio/data/projects.js의 projects 배열에 신규 프로젝트 항목이 존재하는지 확인"
      - "필수 필드 누락 확인: id, number, title, subtitle, phase, difficulty, status, description, concepts, path"
      - "subExamples 배열이 있으면 각 항목에 title, difficulty, status 필드 확인"
      - "phase 값이 phases 배열의 유효한 id인지 확인"
      - "path가 실제 디렉토리를 가리키는지 확인"

  card-rendering:
    description: "카드 렌더링 검증"
    items:
      - "card__subtitle이 표시되는지 확인 (subtitle 필드가 있을 때)"
      - "card__link 텍스트가 '학습 시작하기 📚'인지 확인 ('폴더 열기' 아님)"
      - "concept-tag 폰트 크기가 0.75rem 이상인지 확인"
      - "sub-progress-text 폰트 크기가 0.8rem 이상인지 확인"
      - "카드에 cursor: pointer가 적용되어 있는지 확인"

  accessibility:
    description: "접근성 검증"
    items:
      - "skip-link가 index.html body 첫 번째 요소로 존재하는지 확인"
      - "filter-btn padding이 10px 16px 이상인지 확인 (터치 타겟)"
      - "filter-btn font-size가 0.85rem 이상인지 확인"
      - "timeline-label font-size가 0.8rem 이상인지 확인"
      - "모든 interactive 요소에 aria-label 또는 명시적 텍스트가 있는지 확인"
      - "prefers-reduced-motion 미디어 쿼리가 존재하는지 확인"

  welcome-onboarding:
    description: "온보딩 웰컴 검증"
    items:
      - "renderWelcome 함수가 render()에서 호출되는지 확인"
      - "localStorage 키 'studio-welcome-dismissed'로 닫기 상태 관리"
      - "난이도 설명(⭐ = 쉬움 등)이 웰컴 박스에 포함되어 있는지 확인"

  timeline:
    description: "타임라인 검증"
    items:
      - "타임라인 노드에 title 속성(tooltip)이 '난이도: ... / 상태: ...' 형식인지 확인"
      - "모바일(640px 이하)에서 스크롤 힌트 그라데이션이 표시되는지 확인"
      - "신규 프로젝트가 타임라인에 올바른 순서로 나타나는지 확인"

  mobile-responsive:
    description: "모바일 반응형 검증"
    items:
      - "640px 이하에서 filter-bar가 column 방향인지 확인"
      - "640px 이하에서 timeline-section .container::after가 display: block인지 확인"
      - "카드 그리드가 768px 이하에서 1열, 768px~1024px에서 2열, 1024px 이상에서 3열인지 확인"

checklist:
  description: "프로젝트 추가/변경 후 체크리스트"
  items:
    - label: "projects.js 데이터 동기화"
      check: "신규 프로젝트가 projects 배열에 추가됨, 필수 필드 모두 존재"
    - label: "카드 렌더링"
      check: "부제목 표시, '학습 시작하기' 링크, 개념 태그 가독성"
    - label: "타임라인 동기화"
      check: "신규 노드 표시, tooltip 정보, 순서 정확"
    - label: "접근성 유지"
      check: "스킵 링크, 터치 타겟, 키보드 탐색, aria-label"
    - label: "모바일 레이아웃"
      check: "375px 뷰포트에서 필터/카드/타임라인 정상 표시"
    - label: "온보딩 유지"
      check: "웰컴 박스 표시/닫기/localStorage 동작"
    - label: "다크 모드"
      check: "라이트/다크 모드 전환 시 모든 요소 정상 표시"

examples:
  good:
    - |
      # 새 프로젝트 추가 시
      1. projects/09-new-feature/ 디렉토리 생성
      2. README.md 작성
      3. studio/data/projects.js에 항목 추가 (subtitle 포함)
      4. 시각화 검증 루틴 실행 → 7개 체크리스트 통과
    - |
      # 스튜디오 기능 변경 시
      1. CSS/JS 수정
      2. 시각화 검증 루틴 실행
      3. 접근성 기준 미달 항목 보완
  bad:
    - "projects.js에 subtitle 필드 누락한 채 추가"
    - "카드 링크 텍스트를 '폴더 열기'로 되돌림"
    - "concept-tag 폰트를 0.7rem 이하로 축소"
    - "skip-link 제거"

exceptions:
  - "데이터만 수정하고 렌더링 로직에 변화가 없는 경우, 카드/타임라인 렌더링 검증만 수행"
  - "CSS만 수정하고 데이터에 변화가 없는 경우, 데이터 동기화 검증 생략"

created: "2026-02-10T00:00:00Z"
updated: "2026-02-10T00:00:00Z"
scope: project
enabled: true

metadata:
  version: "1.0.0"
  status: active
  author: "@kent"

platforms:
  claude:
    enabled: true
